### ISSUE TITLE
What's the long term plan here?

### ISSUE THREAD

**Issue by cdubz** [piepworks/listsofbooks-roadmap#2]
👋 Wandered in via GH recommendations and like the design and simplicity of Lists of Books. I wasn't able to tell from the roadmap but are planning to productize this like Cassette Nest?

**Comment by trey** [comment]
Hi! Thanks for stopping by! The only plan for Lists of Books is to make commissions from Bookshop.org and donations on Ko-fi.

Glad you like the design and simplicity :)

**Comment by cdubz** [comment]
Makes sense. The idea just made me want to curate my own lists 😄

I'll make a feature request for one I would be interested in and use...

**Comment by trey** [comment]
Sounds good! Please do
